rootLogger.level = warn
rootLogger.appenderRef.stderr.ref = stderr

appender.stderr.type = Console
appender.stderr.name = stderr
appender.stderr.target = SYSTEM_ERR
appender.stderr.layout.type = PatternLayout
appender.stderr.layout.pattern = %d{yy/MM/dd HH:mm:ss} %p %c{1}: %m%n%ex

logger.nativeCodeLoader.name = org.apache.hadoop.util.NativeCodeLoader
logger.nativeCodeLoader.level = error
